name: jsdoc
on:
 push:
   branches:
     - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: jsdoc
      uses: codevise/documentation-js-action@v1
      with:
        input: ./src
        output: ./docs
        config: ./jsdoc.json
